import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import { StoreProvider } from 'app/providers/store';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const satoshi = localFont({
  src: [
    {
      path: '../fonts/Satoshi-Regular.woff2',
      weight: '400',
      style: 'regular',
    },
    {
      path: '../fonts/Satoshi-Medium.woff2',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../fonts/Satoshi-Bold.woff2',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../fonts/Satoshi-Black.woff2',
      weight: '900',
      style: 'black',
    },
  ],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang='en'>
        <body className={` ${satoshi.className} antialiased`}>{children}</body>
      </html>
    </StoreProvider>
  );
}
